### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by achillesrasquinha** [achillesrasquinha/autopsy#1]
# Build
- [ ] Auto Build
- [ ] Auto Dependency Scanning

# Test
- [ ] Auto Test
- [ ] Auto Browser Performance Testing
- [ ] Auto Code Intelligence
- [ ] Auto Code Quality
- [ ] Auto Container Scanning
- [ ] Auto License Compliance

# Deploy
- [ ] Auto Review Apps
- [ ] Auto Deploy

# Monitor
- [ ] Auto Monitoring
